name: test

on:
  push:
    branches:
    - "main"
    - "release-v**"
  pull_request:
    branches:
    - "*"

jobs:
  test:
    name: Test
    # This job runs on Linux
    runs-on: ubuntu-latest
    container: golang:1.16
    steps:
      - uses: actions/checkout@v2   
      - name: Install AWS CLI,  curl and httpie
        run: |
          apt-get update 
          apt-get install -y curl python3-pip python3 unzip
          pip3 install --user httpie
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "/tmp/awscliv2.zip" 
          unzip /tmp/awscliv2.zip -d /tmp
          /tmp/aws/install
          aws --version
      - name: Test
        run: make test
        env:
          GO111MODULE: "on"
          WAIT_TIME_MS: "5000"
          GO_BIN: ${{ github.workspace }}/app
          MAIN_DIR: ${{ github.workspace }}
          AWS_ACCESS_KEY_ID: 0
          AWS_SECRET_ACCESS_KEY: 0
          AWS_REGION: eu-west-1
      - uses: codecov/codecov-action@v2
        with:
          files: ./coverage.out