name: test

on:
  push:
    branches:
    - "main"
    - "release-v**"
  pull_request:
    branches:
    - "*"

jobs:
  test:
    name: Test
    # This job runs on Linux
    runs-on: ubuntu-latest
    container: golang:1.19
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install miscellaneous
        run: |
          apt-get update 
          apt-get install -y curl python3-pip python3 unzip
          pip3 install --user httpie
          echo "configure git locally"
      - name: Test
        run: make test
        env:
          GO111MODULE: "on"
          GO_BIN: ${{ github.workspace }}/app
          MAIN_DIR: ${{ github.workspace }}
      - name: Build example application
        run: make build
        env:
          GIT_CURL_VERBOSE: 1
          GIT_TRACE: 1
          GO111MODULE: "on"
          GO_BIN: ${{ github.workspace }}/app
          MAIN_DIR: ${{ github.workspace }}
      - uses: codecov/codecov-action@v2
        with:
          files: ./coverage.out